name: Cleanup Old Screenshots

on:
  schedule:
    - cron: "0 5 * * *"  # Daily at 05:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Delete files older than 7 days based on filename
        run: |
          import os
          from datetime import datetime, timedelta

          folder = "fabric_status"
          cutoff_date = datetime.now() - timedelta(days=7)

          deleted = False
          for file in os.listdir(folder):
              if file.startswith("fabric_status_") and file.endswith(".png"):
                  date_str = file[len("fabric_status_"):-4]
                  try:
                      file_dt = datetime.strptime(date_str, "%Y%m%d_%H%M")
                      if file_dt < cutoff_date:
                          os.remove(os.path.join(folder, file))
                          print(f"Deleted: {file}")
                          deleted = True
                  except ValueError:
                      print(f"Skipping invalid file: {file}")

          if not deleted:
              print("No files deleted.")
        shell: python

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ $(git status --porcelain) ]]; then
            git add fabric_status
            git commit -m "Auto-cleanup: remove screenshots older than 7 days"
            git push
          else
            echo "No changes to commit."
