name: Cleanup Old Fabric Status PNGs

on:
  schedule:
    - cron: "0 5 * * *"  # Daily at 05:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Delete old PNG files based on filename
        run: |
          import os
          from datetime import datetime, timedelta

          folder = "fabric_status"
          if not os.path.exists(folder):
              raise FileNotFoundError(f"Folder not found: {folder}")

          cutoff = datetime.now() - timedelta(days=14)
          deleted_files = []

          for file in os.listdir(folder):
              if file.startswith("fabric_status_") and file.endswith(".png"):
                  try:
                      timestamp = file[len("fabric_status_"):-4]  # remove prefix and .png
                      file_date = datetime.strptime(timestamp, "%Y%m%d_%H%M")
                      if file_date < cutoff:
                          os.remove(os.path.join(folder, file))
                          deleted_files.append(file)
                  except Exception as e:
                      print(f"Skipping {file} due to error: {e}")

          if deleted_files:
              print("Deleted files:")
              for f in deleted_files:
                  print(f" - {f}")
          else:
              print("No files deleted.")
        shell: python

      - name: Commit and push deleted files if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          CHANGES=$(git status --porcelain)

          if [ ! -z "$CHANGES" ]; then
            git add fabric_status
            git commit -m "Auto-cleanup: delete PNGs older than 14 days from fabric_status"
            git push
          else
            echo "No changes to commit."
          fi
