name: Scrape Microsoft Fabric Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas playwright
          playwright install chromium

      - name: Run scraper
        run: python scrape_fabric_status.py

      - name: Commit and push CSV file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Add new Fabric status snapshot [skip ci]" || echo "No changes to commit"
          git push
